---
variables:
  GITHUB_REPO: "git@github.com:thorian93/ansible-role-journald.git"

# include:
#   - project: 'configurations/gitlab-ci'
#     ref: master
#     file: 'thorian-linting-to-github.gitlab-ci.yml'

stages:
  - cleanup
  - linting
  - deploy

clean-build-area:
  stage: cleanup
  tags:
    - shell
  script:
    - rm -rf ./*
    - rm -rf ./.git/

ansible-lint:
  stage: linting
  tags:
    - shell
  script:
    - ansible-lint tasks/*.yml

yaml-lint:
  stage: linting
  tags:
    - shell
  script:
    - yamllint tasks/*.yml

shell-lint:
  stage: linting
  tags:
    - shell
  script:
    - find ./ -name "*.sh" -exec shellcheck {} \;

deploy-github:
  stage: deploy
  tags:
    - shell
  script:
    - git remote -v
    - git remote set-url --push origin $GITHUB_REPO
    - git remote -v
    # - git add --all
    # - git commit -m $CI_COMMIT_MESSAGE
    - git push origin HEAD:$CI_COMMIT_REF_NAME
