---
variables:
  GITHUB_REPO: "git@github.com:thorian93/ansible-role-journald.git"

include:
  - project: 'configurations/gitlab-ci'
    ref: master
    file: 'thorian-linting-to-github.gitlab-ci.yml'
